version: '3'

services:
    mongo:
        image: mongo:4.4.3
        container_name: mongo-remap
        env_file:
            - .env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=hsap_remap_2020 # database name you want to make
        ports:
          - "27017:27017"
        volumes:
            - '~/mongo-database-remap2020:/data/db'
            #- ./mongo-express/docker-entrypoint.sh:/docker-entrypoint.sh
            #- ./mongo-init/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

    mongo-express:
        image: mongo-express:0.54.0
        container_name: mongoex-remap
        env_file:
            - .env
        environment:
          - ME_CONFIG_MONGODB_SERVER=mongo
          - ME_CONFIG_MONGODB_PORT=27017
          - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
          - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
          - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
          - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
          - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
          - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
          - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
          - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
        depends_on:
            - mongo
        ports:
          - "8081:8081"
