version: '3.0'

services:
    mongo:
        container_name: mongo-remap
        image: mongo:4.4.3
        env_file:
          - .env
        environment:
          - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
          - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
          - MONGO_INITDB_DATABASE=remap2020 
        ports:
          - "27017:27017"
        volumes:
          - /Users/benoit/mongo-database-remap2020:/data/db
        networks: 
          - mongo-compose-network

    mongo-express:
        image: mongo-express:0.54.0
        container_name: mongoex-remap
        env_file:
            - .env
        environment:
          - ME_CONFIG_MONGODB_SERVER=mongo-remap
          - ME_CONFIG_MONGODB_PORT=27017
          - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
          - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
          - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
          - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
          - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
          - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
          - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
          - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
        depends_on:
          - "mongo"
        volumes:
          - /Users/benoit/mongo-database-remap2020:/data/db
        ports:
          - "8081:8081"
        networks: 
          - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge